services:
  linter:
    image: golangci/golangci-lint:v1.61-alpine
    profiles: [ "local" ]
    working_dir: /app
    command: [ "golangci-lint", "run", "--timeout=10m", "--color=always" ]
    volumes:
      - .:/app
      - ~/.cache/golangci-lint/:/root/.cache
    environment:
      GOFLAGS: "-buildvcs=false"
