name: Init Go Environment
description: Initialize a preconfigured Go environment with cache
# Dummy commit
runs:
  using: "composite"
  steps:
    - name: Setup Go Build Environment
      id: setup_go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
