name: release

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout
  issues: read
  pull-requests: read

jobs:
  bump-tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.7.0
        name: Bump and Tag Version
        id: bump
        with:
          mode: bump
          repo-token:  ${{ secrets.GA_ACCESS_TOKEN }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          require-release-notes: true
          release-notes-prefix: ''
          release-notes-suffix: ''
          with-v: true
    outputs:
      version: ${{ steps.bump.outputs.version }}
